esp_toml_version = 1.0

firmware_images_url = "https://daniel-maiorano.github.io/esp-launchpad/images/"

supported_apps = ["CGWizard-NG Front"]

[Matter-AllClustersApp-TE9]
chipsets = ["ESP32-C6"]
image.esp32-c6 = "CGWizardNG-ESP-F.bin"
