esp_toml_version = 1.0

firmware_images_url = "https://adwait-esp.github.io/flasher/images/"

supported_apps = ["RainMaker-Fan", "RainMaker-GPIO", "RainMaker-Homekit-Switch", "RainMaker-Led-Light", "RainMaker-Multi-Device", "RainMaker-Switch", "RainMaker-Temperature-Sensor"]


[RainMaker-Fan]
chipsets = ["ESP32", "ESP32-S2", "ESP32-C3"]
image.esp32 = "esp32_rainmaker_fan_merged.bin"
image.esp32-s2 = "esp32s2_rainmaker_fan_merged.bin"
image.esp32-c3 = "esp32c3_rainmaker_fan_merged.bin"
android_app_url = "https://play.google.com/store/apps/details?id=com.espressif.rainmaker"
ios_app_url = "https://apps.apple.com/app/esp-rainmaker/id1497491540"

[RainMaker-GPIO]
chipsets = ["ESP32", "ESP32-S2", "ESP32-C3"]
image.esp32 = "esp32_rainmaker_gpio_merged.bin"
image.esp32-s2 = "esp32s2_rainmaker_gpio_merged.bin"
image.esp32-c3 = "esp32c3_rainmaker_gpio_merged.bin"
android_app_url = "https://play.google.com/store/apps/details?id=com.espressif.rainmaker"
ios_app_url = "https://apps.apple.com/app/esp-rainmaker/id1497491540"

[RainMaker-Homekit-Switch]
chipsets = ["ESP32", "ESP32-S2", "ESP32-C3"]
image.esp32 = "esp32_rainmaker_homekit_switch_merged.bin"
image.esp32-s2 = "esp32s2_rainmaker_homekit_switch_merged.bin"
image.esp32-c3 = "esp32c3_rainmaker_homekit_switch_merged.bin"
android_app_url = "https://play.google.com/store/apps/details?id=com.espressif.rainmaker"
ios_app_url = "https://apps.apple.com/app/esp-rainmaker/id1497491540"

[RainMaker-Led-Light]
chipsets = ["ESP32", "ESP32-S2", "ESP32-C3"]
image.esp32 = "esp32_rainmaker_led_light_merged.bin"
image.esp32-s2 = "esp32s2_rainmaker_led_light_merged.bin"
image.esp32-c3 = "esp32c3_rainmaker_led_light_merged.bin"
android_app_url = "https://play.google.com/store/apps/details?id=com.espressif.rainmaker"
ios_app_url = "https://apps.apple.com/app/esp-rainmaker/id1497491540"

[RainMaker-Multi-Device]
chipsets = ["ESP32", "ESP32-S2", "ESP32-C3"]
image.esp32 = "esp32_rainmaker_multi_device_merged.bin"
image.esp32-s2 = "esp32s2_rainmaker_multi_device_merged.bin"
image.esp32-c3 = "esp32c3_rainmaker_multi_device_merged.bin"
android_app_url = "https://play.google.com/store/apps/details?id=com.espressif.rainmaker"
ios_app_url = "https://apps.apple.com/app/esp-rainmaker/id1497491540"

[RainMaker-Switch]
chipsets = ["ESP32", "ESP32-S2", "ESP32-C3"]
image.esp32 = "esp32_rainmaker_switch_merged.bin"
image.esp32-s2 = "esp32s2_rainmaker_switch_merged.bin"
image.esp32-c3 = "esp32c3_rainmaker_switch_merged.bin"
android_app_url = "https://play.google.com/store/apps/details?id=com.espressif.rainmaker"
ios_app_url = "https://apps.apple.com/app/esp-rainmaker/id1497491540"

[RainMaker-Temperature-Sensor]
chipsets = ["ESP32", "ESP32-S2", "ESP32-C3"]
image.esp32 = "esp32_rainmaker_temperature_sensor_merged.bin"
image.esp32-s2 = "esp32s2_rainmaker_temperature_sensor_merged.bin"
image.esp32-c3 = "esp32c3_rainmaker_temperature_sensor_merged.bin"
android_app_url = "https://play.google.com/store/apps/details?id=com.espressif.rainmaker"
ios_app_url = "https://apps.apple.com/app/esp-rainmaker/id1497491540"